name: push-message CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

         

      - name: Show commit message
        run: |
          echo "Commit message:"
          echo "${{ github.event.head_commit.message }}"
      
      - name: show branch name
        run: |
          
          echo "Branch name: $ {{ github.ref_name }} " 

      - name: Run test
        run: python test_app.py
